<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class UpdateDesignsFields extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('designs', function (Blueprint $table) {
            $table->string('category')->nullable();
            $table->integer('size')->nullable();
            $table->integer('mMetrics')->nullable();
            $table->decimal('length')->nullable();
            $table->decimal('width')->nullable();
            $table->string('code')->nullable();
            $table->integer('numOrders')->nullable();
            $table->string('materialType')->nullable();
            $table->string('floorsList')->nullable();
            $table->string('baseType')->nullable();
            $table->string('roofType')->nullable();
            $table->decimal('roofSquare')->nullable();
            $table->decimal('mainSquare')->nullable();
            $table->string('baseLength')->nullable();
            $table->string('baseD20')->nullable();
            $table->string('baseD20F')->nullable();
            $table->string('baseD20Rub')->nullable();
            $table->string('baseD20RubF')->nullable();
            $table->string('baseBalk1')->nullable();
            $table->string('baseBalkF')->nullable();
            $table->string('baseBalk2')->nullable();
            $table->integer('wallsOut')->nullable();
            $table->integer('wallsIn')->nullable();
            $table->integer('wallsPerOut')->nullable();
            $table->integer('wallsPerIn')->nullable();
            $table->string('rubRoof')->nullable();
            $table->string('skatList')->nullable();
            $table->string('krovlaList')->nullable();
            $table->string('stropList')->nullable();
            $table->string('stropValue')->nullable();
            $table->string('endovList')->nullable();
            $table->string('metaList')->nullable();
            $table->string('mrKon')->nullable();
            $table->string('mrPlanVetr')->nullable();
            $table->string('mrPlanKar')->nullable();
            $table->string('mrKapelnik')->nullable();
            $table->string('mrEndn')->nullable();
            $table->string('mrEndv')->nullable();
            $table->string('mrSam35')->nullable();
            $table->string('mrSam70')->nullable();
            $table->string('mrPack')->nullable();
            $table->string('mrIzospanAM')->nullable();
            $table->string('mrIzospanAM35')->nullable();
            $table->string('mrLenta')->nullable();
            $table->string('mrRokvul')->nullable();
            $table->string('mrIzospanB')->nullable();
            $table->string('mrIzospanB35')->nullable();
            $table->string('mrPrimUgol')->nullable();
            $table->string('mrPrimNakl')->nullable();
            $table->string('mrUtep200')->nullable();
            $table->string('mrUtep150')->nullable();
            $table->string('srCherep')->nullable();
            $table->string('srKover')->nullable();
            $table->string('srKonK')->nullable();
            $table->string('srMastika1')->nullable();
            $table->string('srMastika')->nullable();
            $table->string('srKonShir')->nullable();
            $table->string('srKonOneSkat')->nullable();
            $table->string('srPlanVetr')->nullable();
            $table->string('srPlanK')->nullable();
            $table->string('srKapelnik')->nullable();
            $table->string('srEndn')->nullable();
            $table->string('srEndv')->nullable();
            $table->string('srGvozd')->nullable();
            $table->string('srSam70')->nullable();
            $table->string('srPack')->nullable();
            $table->string('srIzospanAM')->nullable();
            $table->string('srIzospanAM35')->nullable();
            $table->string('srLenta')->nullable();
            $table->string('srRokvul')->nullable();
            $table->string('srIzospanB')->nullable();
            $table->string('srIzospanB35')->nullable();
            $table->string('srPrimUgol')->nullable();
            $table->string('srPrimNakl')->nullable();
            $table->string('srOSB')->nullable();
            $table->string('srAero')->nullable();
            $table->string('srAeroSkat')->nullable();
            $table->string('srUtep150')->nullable();
            $table->string('srUtep200')->nullable();
            $table->string('pvParts')->nullable();
            $table->string('mvParts')->nullable();
            $table->string('lfLength')->nullable();
            $table->string('lfAngleG')->nullable();
            $table->string('lfAngleT')->nullable();
            $table->string('lfAngleX')->nullable();
            $table->string('lfAngle45')->nullable();
            $table->string('vfLength')->nullable();
            $table->integer('vfCount')->nullable();
            $table->string('vfBalk')->nullable();
            $table->string('mfSquare')->nullable();
            $table->string('meta1')->nullable();
            $table->string('meta2')->nullable();
            $table->string('meta3')->nullable();
            $table->string('meta4')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('designs', function (Blueprint $table) {
            // Drop the newly added columns
            $table->dropColumn([
                'size',
                'mMetrics',
                'length',
                'width',
                'code',
                'numOrders',
                'materialType',
                'floorsList',
                'baseType',
                'roofType',
                'roofSquare',
                'mainSquare',
                'baseLength',
                'baseD20',
                'baseD20F',
                'baseD20Rub',
                'baseD20RubF',
                'baseBalk1',
                'baseBalkF',
                'baseBalk2',
                'wallsOut',
                'wallsIn',
                'wallsPerOut',
                'wallsPerIn',
                'rubRoof',
                'skatList',
                'krovlaList',
                'stropList',
                'endovList',
                'metaList',
                'mrKon',
                'mrPlanVetr',
                'mrPlanKar',
                'mrKapelnik',
                'mrEndn',
                'mrEndv',
                'mrSam35',
                'mrSam70',
                'mrPack',
                'mrIzospanAM',
                'mrIzospanAM35',
                'mrLenta',
                'mrRokvul',
                'mrIzospanB',
                'mrIzospanB35',
                'mrPrimUgol',
                'mrPrimNakl',
                'mrUtep200',
                'mrUtep150',
                'srCherep',
                'srKover',
                'srKonK',
                'srMastika1',
                'srMastika',
                'srKonShir',
                'srKonOneSkat',
                'srPlanVetr',
                'srPlanK',
                'srKapelnik',
                'srEndn',
                'srEndv',
                'srGvozd',
                'srSam70',
                'srPack',
                'srIzospanAM',
                'srIzospanAM35',
                'srLenta',
                'srRokvul',
                'srIzospanB',
                'srIzospanB35',
                'srPrimUgol',
                'srPrimNakl',
                'srOSB',
                'srAero',
                'srAeroSkat',
                'srUtep150',
                'srUtep200',
                'pvParts',
                'mvParts',
                'lfLength',
                'lfAngleG',
                'lfAngleT',
                'lfAngleX',
                'lfAngle45',
                'vfLength',
                'vfCount',
                'vfBalk',
                'mfSquare',
                'meta1',
                'meta2',
                'meta3',
                'meta4',
                'category',
                'stropValue'
            ]);
        });
    }
}
